name: build

on: [push, pull_request]

jobs:
  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [clang64, ucrt64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        install: base-devel git
        pacboy: cc cmake expat fmt gtest libpng ninja pkgconf protobuf
    - name: Prepare
      run: |
        git submodule update --init --depth 1
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        cd vendor/core
        git config core.symlinks true
        MSYS='winsymlinks:nativestrict' git restore --source=HEAD :/ || true
    - name: Build
      run: |
        cmake -B build -G Ninja
        cmake --build build
    - name: Check
      run: |
        ./build/vendor/aapt version
        ./build/vendor/aapt2 version
